/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoungeRouteImport } from './routes/lounge'
import { Route as DemoPaymentRouteImport } from './routes/demo-payment'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppTimeTrackerIndexRouteImport } from './routes/app/time-tracker/index'
import { Route as AppWorkspaceSettingsRouteImport } from './routes/app/workspace/settings'
import { Route as AppWorkspaceMembersRouteImport } from './routes/app/workspace/members'
import { Route as AppWorkspaceCatalogsRouteImport } from './routes/app/workspace/catalogs'
import { Route as AppTimeTrackerWeekRouteImport } from './routes/app/time-tracker/week'
import { Route as AppTimeTrackerMonthRouteImport } from './routes/app/time-tracker/month'
import { Route as AppTimeTrackerDayRouteImport } from './routes/app/time-tracker/day'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoungeRoute = LoungeRouteImport.update({
  id: '/lounge',
  path: '/lounge',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPaymentRoute = DemoPaymentRouteImport.update({
  id: '/demo-payment',
  path: '/demo-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerIndexRoute = AppTimeTrackerIndexRouteImport.update({
  id: '/time-tracker/',
  path: '/time-tracker/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceSettingsRoute = AppWorkspaceSettingsRouteImport.update({
  id: '/workspace/settings',
  path: '/workspace/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceMembersRoute = AppWorkspaceMembersRouteImport.update({
  id: '/workspace/members',
  path: '/workspace/members',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceCatalogsRoute = AppWorkspaceCatalogsRouteImport.update({
  id: '/workspace/catalogs',
  path: '/workspace/catalogs',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerWeekRoute = AppTimeTrackerWeekRouteImport.update({
  id: '/time-tracker/week',
  path: '/time-tracker/week',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerMonthRoute = AppTimeTrackerMonthRouteImport.update({
  id: '/time-tracker/month',
  path: '/time-tracker/month',
  getParentRoute: () => AppRoute,
} as any)
const AppTimeTrackerDayRoute = AppTimeTrackerDayRouteImport.update({
  id: '/time-tracker/day',
  path: '/time-tracker/day',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo-payment': typeof DemoPaymentRoute
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRoute
  '/app/workspace/members': typeof AppWorkspaceMembersRoute
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker/': typeof AppTimeTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo-payment': typeof DemoPaymentRoute
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/auth': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRoute
  '/app/workspace/members': typeof AppWorkspaceMembersRoute
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker': typeof AppTimeTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/demo-payment': typeof DemoPaymentRoute
  '/lounge': typeof LoungeRoute
  '/onboarding': typeof OnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invite/$token': typeof InviteTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/time-tracker/day': typeof AppTimeTrackerDayRoute
  '/app/time-tracker/month': typeof AppTimeTrackerMonthRoute
  '/app/time-tracker/week': typeof AppTimeTrackerWeekRoute
  '/app/workspace/catalogs': typeof AppWorkspaceCatalogsRoute
  '/app/workspace/members': typeof AppWorkspaceMembersRoute
  '/app/workspace/settings': typeof AppWorkspaceSettingsRoute
  '/app/time-tracker/': typeof AppTimeTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/demo-payment'
    | '/lounge'
    | '/onboarding'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/auth/'
    | '/api/auth/$'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/demo-payment'
    | '/lounge'
    | '/onboarding'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/auth'
    | '/api/auth/$'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/demo-payment'
    | '/lounge'
    | '/onboarding'
    | '/app/profile'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/invite/$token'
    | '/auth/'
    | '/api/auth/$'
    | '/app/time-tracker/day'
    | '/app/time-tracker/month'
    | '/app/time-tracker/week'
    | '/app/workspace/catalogs'
    | '/app/workspace/members'
    | '/app/workspace/settings'
    | '/app/time-tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DemoPaymentRoute: typeof DemoPaymentRoute
  LoungeRoute: typeof LoungeRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lounge': {
      id: '/lounge'
      path: '/lounge'
      fullPath: '/lounge'
      preLoaderRoute: typeof LoungeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo-payment': {
      id: '/demo-payment'
      path: '/demo-payment'
      fullPath: '/demo-payment'
      preLoaderRoute: typeof DemoPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/': {
      id: '/app/time-tracker/'
      path: '/time-tracker'
      fullPath: '/app/time-tracker/'
      preLoaderRoute: typeof AppTimeTrackerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/settings': {
      id: '/app/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/app/workspace/settings'
      preLoaderRoute: typeof AppWorkspaceSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/members': {
      id: '/app/workspace/members'
      path: '/workspace/members'
      fullPath: '/app/workspace/members'
      preLoaderRoute: typeof AppWorkspaceMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/catalogs': {
      id: '/app/workspace/catalogs'
      path: '/workspace/catalogs'
      fullPath: '/app/workspace/catalogs'
      preLoaderRoute: typeof AppWorkspaceCatalogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/week': {
      id: '/app/time-tracker/week'
      path: '/time-tracker/week'
      fullPath: '/app/time-tracker/week'
      preLoaderRoute: typeof AppTimeTrackerWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/month': {
      id: '/app/time-tracker/month'
      path: '/time-tracker/month'
      fullPath: '/app/time-tracker/month'
      preLoaderRoute: typeof AppTimeTrackerMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/time-tracker/day': {
      id: '/app/time-tracker/day'
      path: '/time-tracker/day'
      fullPath: '/app/time-tracker/day'
      preLoaderRoute: typeof AppTimeTrackerDayRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppTimeTrackerDayRoute: typeof AppTimeTrackerDayRoute
  AppTimeTrackerMonthRoute: typeof AppTimeTrackerMonthRoute
  AppTimeTrackerWeekRoute: typeof AppTimeTrackerWeekRoute
  AppWorkspaceCatalogsRoute: typeof AppWorkspaceCatalogsRoute
  AppWorkspaceMembersRoute: typeof AppWorkspaceMembersRoute
  AppWorkspaceSettingsRoute: typeof AppWorkspaceSettingsRoute
  AppTimeTrackerIndexRoute: typeof AppTimeTrackerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppTimeTrackerDayRoute: AppTimeTrackerDayRoute,
  AppTimeTrackerMonthRoute: AppTimeTrackerMonthRoute,
  AppTimeTrackerWeekRoute: AppTimeTrackerWeekRoute,
  AppWorkspaceCatalogsRoute: AppWorkspaceCatalogsRoute,
  AppWorkspaceMembersRoute: AppWorkspaceMembersRoute,
  AppWorkspaceSettingsRoute: AppWorkspaceSettingsRoute,
  AppTimeTrackerIndexRoute: AppTimeTrackerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DemoPaymentRoute: DemoPaymentRoute,
  LoungeRoute: LoungeRoute,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  InviteTokenRoute: InviteTokenRoute,
  AuthIndexRoute: AuthIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
